language: rust
rust:
  - stable
  - beta
  - nightly


before_install:
  - curl -O https://github.com/devkitPro/pacman/blob/master/lib/libalpm/alpm.h
    
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true